#server.port=8888
#
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/basketball?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=root
#
#mybatis.mapper-locations=classpath:mappers/*.xml
#mybatis.type-aliases-package=zhanweikai.com.pojo



server:
  port: 8889

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basketball?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: zhanweikai.com.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    延迟加载（优化查询）
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
#   查询为空值时，不显示该字段
    map-underscore-to-camel-case: true